version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .

  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3.7
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libeigen3-dev
      - run: pip3 install -U pytest pytest-cov --user
      - checkout
      - run: pip3 install -r test_requirements.txt --user
      - run: pip3 install . --user
      # The tests
      - run:
          command: pytest --cov accupy
          working_directory: test/
          environment:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
