version: 2

jobs:

  build:
    working_directory: ~/quadpy
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt-get update
      # don't install sympy with apt: it pulls in texlive which takes for ever
      # to download and install
      - run: apt-get install -y git python3-pip pandoc
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install -r test_requirements.txt
      - run: pip3 install .
      # lint
      - run: pylint quadpy/ test/*.py
      # make sure that rst converts correctly
      - run: pip3 install docutils pygments
      - run: make README.rst
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov quadpy
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

# workflow builds don't support forked PRs yet, cf.
# <https://circleci.com/docs/2.0/faq/#can-i-build-fork-prs-using-workflows>.
# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - python2
#       - python3
